name: Update hln commands documentations

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: "20 20 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOURCE_BRANCH: website-docs
      SOURCE_DIR: website-docs
      TARGET_DIR: docs/07-cli/hln/commands
    steps:
      - uses: actions/checkout@v3

      - name: Fetch hln commands documentations
        run: |
          ./scripts/update-cli-docs.sh

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          title: "docs: update hln commands documentations"
          commit-message: "docs: update hln commands documentations"
          base: main
          add-paths: |
            docs/07-cli
