name: Pull hln commands documentations

on:
  schedule:
  - cron: '20 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOURCE_BRANCH: website-docs
      SOURCE_DIR: website-docs
      TARGET_DIR: docs/07-cli/hln/commands
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Create local changes
      run: |
        git clone -b $SOURCE_BRANCH git@github.com:h8r-dev/heighliner.git ../hln
        rm $TARGET_DIR/*.md
        cp ../hln/$SOURCE_DIR/*.md $TARGET_DIR
    - name: Commit files
      run: |
        git config --local user.email "heigliner-robot@h8r.io"
        git config --local user.name "heigliner-robot"
        git add $TARGET_DIR
        git commit -m "Update hln docs" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}