name: Deploy Heighliner website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build

      - name: Install coscmd
        run: pip install coscmd

      - name: Upload Build Static Files to COS
        run: |
          coscmd config -a ${{ secrets.TENCENT_SECRET_ID }} -s ${{ secrets.TENCENT_SECRET_KEY }} -b website-1309519128 -r ap-hongkong --retry 5
          cd build
          coscmd upload -r --delete -y . .

      - name: Install tencentcloud cli
        run: pip install tccli

      - name: Set tencentcloud cli secret
        run: |
          tccli configure set secretId ${{ secrets.TENCENT_SECRET_ID }}
          tccli configure set secretKey ${{ secrets.TENCENT_SECRET_KEY }}

      - name: Refresh cache by cli
        run: |
          tccli cdn PurgePathCache \
          --cli-unfold-argument \
          --FlushType flush \
          --Paths https://heighliner.dev/ \
          https://heighliner.dev/about-us/ \
          https://heighliner.dev/blog/ \
          https://heighliner.dev/contact-us/ \
          https://heighliner.dev/docs/ \
          https://heighliner.dev/join-us/ \
          https://heighliner.dev/resources/ \
          https://heighliner.dev/search/ \
          https://heighliner.dev/version/
